.TH MSEED2ESYNC 1 2023/07/25
.SH NAME
Create an Enhanced SYNC Listing from miniSEED file(s)

.SH SYNOPSIS
.nf
mseed2esync [options] file1 [file2 file3 ...]

.fi
.SH DESCRIPTION
\fBmseed2esync\fP reads miniSEED, optionally subsetting to specific
time ranges or channels, and prints an Enhanced SYNC listing.

An Enhanced SYNC Listing includes the SEED quality indicator and an
MD5 hash of the sample values.  The MD5 hash of the sample values
allows time series segments to be compared without directly comparing
the sample values.

IMPORTANT: the MD5 hashing employed is dependent on the binary
representation of the sample values on a given architecture.  Most
architectures should generate comparable values but some may not,
particularly for float type samples.

The publication version, or data quality codes, is included in the
SYNC listing in the field historically used for "DCC Tape Number".

The MD5 sample value hash is included in the SYNC listing in the field
historically used for "DMC Volume Number".

If '-' is specified standard input will be read.  Multiple input files
will be processed in the order specified.

Files on the command line prefixed with a '@' character are input list
files and are expected to contain a simple list of input files, see
\fBINPUT LIST FILE\fR for more details.

.SH OPTIONS

.IP "-V         "
Print program version and exit.

.IP "-h         "
Print program usage and exit.

.IP "-v         "
Be more verbose.  This flag can be used multiple times ("-v -v" or
"-vv") for more verbosity.

.IP "-D \fIDCCID\fP"
Specify the a data center identifier to place in the SYNC file header.
If not specified it will be left empty in the header.

.IP "-C         "
Compare the sample values between each segment of data being
processed, useful for diagnosing differences.  If all of the segments
processed match the exit value of the program will be 0, otherwise 1.

.IP "-ts \fItime\fP"
Limit processing to miniSEED records that contain or start after
\fItime\fP.  The format of the \fItime\fP arguement
is: 'YYYY[-MM-DDThh:mm:ss.ffff], or 'YYYY[,DDD,HH,MM,SS,FFFFFF]',
or Unix/POSIX epoch seconds.

.IP "-te \fItime\fP"
Limit processing to miniSEED records that contain or end before
\fItime\fP.  The format of the \fItime\fP arguement
is: 'YYYY[-MM-DDThh:mm:ss.ffff], or 'YYYY[,DDD,HH,MM,SS,FFFFFF]',
or Unix/POSIX epoch seconds.

.IP "-m \fImatch\fP"
Limit processing to miniSEED records that contain the \fImatch\fP
pattern, which is applied to the Source Identifier for each record,
often following this pattern:
'FDSN:<network>_<station>_<location>_<band>_<source>_<subsource>'

.IP "-r \fIreject\fP"
Limit processing to miniSEED records that do _not_ contain the
\fIreject\fP pattern, which is applied to the the Source Identifier
for each record, often following this pattern:
'FDSN:<network>_<station>_<location>_<band>_<source>_<subsource>'

.IP "-tt \fIsecs\fP"
Specify a time tolerance for constructing continous trace
segments. The tolerance is specified in seconds.  The default
tolerance is 1/2 of the sample period.

.IP "-rt \fIdiff\fP"
Specify a sample rate tolerance for constructing continous trace
segments. The tolerance is specified as the difference between two
sampling rates.  The default tolerance is tested as: (abs(1-sr1/sr2) <
0.0001).

.SH "INPUT FILES"

An input file name may be followed by an \fB@\fP charater followed by
a byte range in the pattern \fBSTART[-END]\fP, where the END offset is
optional.  As an example an input file specified as
\fBANMO.mseed@8192\fP would result in the file \fBANMO.mseed\fP being
read starting at byte 8192.  An optional end offset can be specified,
e.g. \fBANMO.mseed@8192-12288\fP would start reading at offset 8192
and stop after offset 12288.

.SH "INPUT LIST FILE"
A list file can be used to specify input files, one file per line.
The initial '@' character indicating a list file is not considered
part of the file name.  As an example, if the following command line
option was used:

.nf
\fB@files.list\fP
.fi

The 'files.list' file might look like this:

.nf
data/day1.mseed
data/day2.mseed
data/day3.mseed
.fi

.SH AUTHOR
.nf
Chad Trabant
EarthScope Data Services
.fi
